import type { ITableColumn, ITableRowValueType } from '../model';
import { setPositionColumns } from '../utils';
import { ColumnType } from './cell-types';

export const INITIAL_ALL_TABLE_COLUMNS: ITableColumn[] = setPositionColumns([
	{
		id: '1',
		columnType: ColumnType.SYMBOL,
		type: 'symbol',
		order: 1,
		columnName: 'symbol',
		displayColumnName: 'Symbol',
		displayShortColumnName: 'Symbol',
		isToggleable: false,
		isDraggable: false,
		isShow: true,
		position: 0,
		group: {
			name: 'symbol',
		},
	},
	{
		id: '2',
		columnType: ColumnType.PRICE_CURRENT,
		type: 'number',
		order: 2,
		columnName: 'price',
		displayColumnName: 'Price',
		displayShortColumnName: 'Price',
		group: {
			name: 'price',
		},
		isShow: true,
		isToggleable: true,
		isDraggable: true,
		position: 1,
	},
	{
		id: '3',
		columnType: ColumnType.CHANGE_PRICE_24H_PERCENT,
		type: 'percent',
		order: 3,
		columnName: 'chg24h',
		displayColumnName: 'Change 24h%',
		displayShortColumnName: 'Chg 24h%',
		isShow: true,
		isToggleable: true,
		isDraggable: true,
		position: 2,
		group: {
			name: 'change',
			order: 2,
		},
	},
	{
		id: '4',
		columnType: ColumnType.CHANGE_PRICE_1H_PERCENT,
		type: 'percent',
		order: 4,
		columnName: 'chg1h',
		displayColumnName: 'Change 1h%',
		displayShortColumnName: 'Chg 1h%',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 3,
		group: {
			name: 'change',
			order: 1,
		},
	},
	{
		id: '5',
		columnType: ColumnType.CHANGE_PRICE_7D_PERCENT,
		type: 'percent',
		order: 5,
		columnName: 'chg7d',
		displayColumnName: 'Change 7d%',
		displayShortColumnName: 'Chg 7d%',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 4,
		// type: 'percent',
		group: {
			name: 'change',
		},
	},
	{
		id: '6',
		columnType: ColumnType.VOLUME_24H,
		type: 'number',
		order: 6,
		columnName: 'volume24h',
		displayColumnName: 'Volume 24h',
		displayShortColumnName: 'Vol 24h',
		isShow: true,
		isToggleable: true,
		isDraggable: true,
		position: 5,
		group: {
			name: 'volume',
		},
	},
	{
		id: '7',
		columnType: ColumnType.MARKET_CAP24H,
		type: 'number',
		order: 7,
		columnName: 'marketCap24h',
		displayColumnName: 'Market cap 24h',
		displayShortColumnName: 'MCap 24h',
		isShow: true,
		isToggleable: true,
		isDraggable: true,
		position: 6,
		group: {
			name: 'MCap',
		},
	},
	{
		id: '8',
		columnType: ColumnType.LISTING_DATE,
		type: 'text',
		order: 8,
		columnName: 'listingDate',
		displayColumnName: 'Listing Date',
		displayShortColumnName: 'Listing Date',
		isShow: true,
		isToggleable: true,
		isDraggable: true,
		position: 7,
		group: {
			name: 'text',
		},
	},
	{
		id: '9',
		columnType: ColumnType.CHANGE_PRICE_30D_PERCENT,
		type: 'percent',
		order: 9,
		columnName: 'chg30d',
		displayColumnName: 'Change 30d%',
		displayShortColumnName: 'Chg 30d%',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 8,
		group: {
			name: 'change',
		},
	},
	{
		id: '10',
		columnType: ColumnType.VOLUME_AVG10D,
		type: 'number',
		order: 10,
		columnName: 'volume',
		displayColumnName: 'Volume Avg 10d',
		displayShortColumnName: 'Vol Avg',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 9,
		group: {
			name: 'volume',
		},
	},
	{
		id: '11',
		columnType: ColumnType.MARKET_CAP24H,
		type: 'number',
		order: 11,
		columnName: 'marketCap',
		displayColumnName: 'Market Cap',
		displayShortColumnName: 'MCap',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 10,
		group: {
			name: 'MCap',
		},
	},
	{
		id: '12',
		columnType: ColumnType.CHANGE_PRICE_24H,
		type: 'number',
		order: 12,
		columnName: 'changePrice24h',
		displayColumnName: 'Change 24h $',
		displayShortColumnName: 'Chg 24h $',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 11,
		group: {
			name: 'change',
		},
	},
	{
		id: '13',
		columnType: ColumnType.OPEN_PRICE,
		type: 'number',
		order: 13,
		columnName: 'openPrice',
		displayColumnName: 'Open Price',
		displayShortColumnName: 'Open',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 12,
		group: {
			name: 'price',
		},
	},
	{
		id: '14',
		columnType: ColumnType.CLOSE_PRICE,
		type: 'number',
		order: 14,
		columnName: 'closePrice',
		displayColumnName: 'Close Price',
		displayShortColumnName: 'Close',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 13,
		group: {
			name: 'price',
		},
	},
	{
		id: '15',
		columnType: ColumnType.PRICE_MIN24H,
		type: 'number',
		order: 15,
		columnName: 'priceMin24h',
		displayColumnName: 'Min 24h',
		displayShortColumnName: 'Min 24h',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 14,
		group: {
			name: 'price',
		},
	},
	{
		id: '16',
		columnType: ColumnType.PRICE_MAX24H,
		type: 'number',
		order: 16,
		columnName: 'priceMax24h',
		displayColumnName: 'Max 24h',
		displayShortColumnName: 'Max 24h',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 15,
		group: {
			name: 'price',
		},
	},
	{
		id: '17',
		columnType: ColumnType.PRICE_MIN1Y,
		type: 'number',
		order: 17,
		columnName: 'priceMin1y',
		displayColumnName: 'Min 1Y',
		displayShortColumnName: 'Min 1Y',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 16,
		group: {
			name: 'price',
		},
	},
	{
		id: '18',
		columnType: ColumnType.PRICE_MAX1Y,
		type: 'number',
		order: 18,
		columnName: 'priceMax1y',
		displayColumnName: 'Max 1Y',
		displayShortColumnName: 'Max 1Y',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 17,
		group: {
			name: 'price',
		},
	},
	{
		id: '19',
		columnType: ColumnType.PRICE_AVG50D,
		type: 'number',
		order: 19,
		columnName: 'priceAvg50d',
		displayColumnName: 'Avg 50d',
		displayShortColumnName: 'Avg 50d',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 18,
		group: {
			name: 'price',
		},
	},
	{
		id: '20',
		columnType: ColumnType.PRICE_AVG200D,
		type: 'number',
		order: 20,
		columnName: 'priceAvg200d',
		displayColumnName: 'Avg 200d',
		displayShortColumnName: 'Avg 200d',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 19,
		group: {
			name: 'price',
		},
	},
	{
		id: '21',
		columnType: ColumnType.VOLUME_REL10D,
		type: 'number',
		order: 21,
		columnName: 'volumeRel10d',
		displayColumnName: 'Vol Rel 10d',
		displayShortColumnName: 'Vol Rel',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 20,
		group: {
			name: 'volume',
		},
	},
	{
		id: '22',
		columnType: ColumnType.VOLUME_AVG10D,
		type: 'number',
		order: 22,
		columnName: 'volumeAvg10d',
		displayColumnName: 'Vol Avg 10d',
		displayShortColumnName: 'Vol Avg 10d',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 21,
		group: {
			name: 'volume',
		},
	},
	{
		id: '23',
		columnType: ColumnType.RSI_NUMBER,
		type: 'number',
		order: 23,
		columnName: 'rsi',
		displayColumnName: 'RSI',
		displayShortColumnName: 'RSI',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 22,
		group: {
			name: 'indicators',
		},
	},
	{
		id: '24',
		columnType: ColumnType.BETA5Y,
		type: 'number',
		order: 24,
		columnName: 'beta',
		displayColumnName: 'Beta 5Y',
		displayShortColumnName: 'Beta',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 23,
		group: {
			name: 'indicators',
		},
	},
	{
		id: '25',
		columnType: ColumnType.PRICE_1Y_RANGE,
		type: 'range',
		order: 25,
		columnName: 'range1y',
		displayColumnName: '1Y Range',
		displayShortColumnName: '1Y Range',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 24,
		group: {
			name: 'price',
		},
	},
	{
		id: '26',
		columnType: ColumnType.PRICE_24H_CHART,
		type: 'chart',
		order: 26,
		columnName: 'chart24h',
		displayColumnName: 'Chart 24h',
		displayShortColumnName: 'Chart 24h',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 25,
		group: {
			name: 'charts',
		},
	},
	{
		id: '27',
		columnType: ColumnType.PRICE_7D_CHART,
		type: 'chart',
		order: 27,
		columnName: 'chart7d',
		displayColumnName: 'Chart 7d',
		displayShortColumnName: 'Chart 7d',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 26,
		group: {
			name: 'charts',
		},
	},
	{
		id: '28',
		columnType: ColumnType.PRICE_30D_CHART,
		type: 'chart',
		order: 28,
		columnName: 'chart30d',
		displayColumnName: 'Chart 30d',
		displayShortColumnName: 'Chart 30d',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 27,
		group: {
			name: 'charts',
		},
	},
	{
		id: '29',
		columnType: ColumnType.RSI_CHART,
		type: 'chart',
		order: 29,
		columnName: 'rsiChart',
		displayColumnName: 'RSI Chart',
		displayShortColumnName: 'RSI Chart',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 28,
		group: {
			name: 'charts',
		},
	},
	{
		id: '30',
		columnType: ColumnType.LAST_DIVIDEND,
		type: 'text',
		order: 30,
		columnName: 'lastDividend',
		displayColumnName: 'Last Dividend',
		displayShortColumnName: 'Dividend',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 29,
		group: {
			name: 'company',
		},
	},
	{
		id: '31',
		columnType: ColumnType.COMPANY_EMPLOYEES,
		type: 'text',
		order: 31,
		columnName: 'employees',
		displayColumnName: 'Employees',
		displayShortColumnName: 'Employees',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 30,
		group: {
			name: 'company',
		},
	},
	{
		id: '32',
		columnType: ColumnType.COMPANY_IPO_DATE,
		type: 'text',
		order: 32,
		columnName: 'ipoDate',
		displayColumnName: 'IPO Date',
		displayShortColumnName: 'IPO Date',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 31,
		group: {
			name: 'company',
		},
	},
	{
		id: '33',
		columnType: ColumnType.COMPANY_SECTOR,
		type: 'text',
		order: 33,
		columnName: 'sector',
		displayColumnName: 'Sector',
		displayShortColumnName: 'Sector',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 32,
		group: {
			name: 'company',
		},
	},
	{
		id: '34',
		columnType: ColumnType.COMPANY_INDUSTRY,
		type: 'text',
		order: 34,
		columnName: 'industry',
		displayColumnName: 'Industry',
		displayShortColumnName: 'Industry',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 33,
		group: {
			name: 'company',
		},
	},
	{
		id: '35',
		columnType: ColumnType.SOURCE,
		type: 'text',
		order: 35,
		columnName: 'source',
		displayColumnName: 'Source',
		displayShortColumnName: 'Source',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 34,
		group: {
			name: 'meta',
		},
	},
	{
		id: '36',
		columnType: ColumnType.UPDATE_DATE,
		type: 'text',
		order: 36,
		columnName: 'updateDate',
		displayColumnName: 'Update Date',
		displayShortColumnName: 'Updated',
		isShow: false,
		isToggleable: true,
		isDraggable: true,
		position: 35,
		group: {
			name: 'meta',
		},
	},
]);

export const INITIAL_ACTIVE_TABLE_COLUMNS: ITableColumn[] = setPositionColumns(
	INITIAL_ALL_TABLE_COLUMNS.filter(item => item.isShow),
);

export const ACCEPT_COLUMNS_TYPES_SORT: ITableRowValueType[] = [
	'symbol',
	'number',
	'percent',
	'text',
	'chart',
	'range',
];
