workflow:
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[ci skip\]/ || $CI_COMMIT_MESSAGE =~ /\[skip ci\]/'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        IMAGE_TAG: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME-$CI_PIPELINE_IID
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event"'
      variables:
        IMAGE_TAG: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_IID

variables:
  GIT_CLEAN_FLAGS: -ffdx -e frontend/node_modules/
  GITLAB_TOKEN: $GITLAB_TOKEN
  MANIFEST_BRANCH_REPO: main

include:
  - local: "/frontend/.gitlab-ci/snippets/setup.yml"
  - local: "/frontend/.gitlab-ci/snippets/lint.yml"

before_script:
  - cd frontend

stages:
  - setup
  - lint
  - deploy
  - build

deploy:
  stage: deploy
  image: alpine:3.21
  script:
    - apk add --no-cache git
    - git init repo
    - cd repo
    - git config user.email "ci@planet9.uk"
    - git config user.name "GitLab CI"
    - git remote add origin https://oauth2:$GITLAB_TOKEN@gitlab.planet9.uk/devops/k8s-manifests.git

    - git config core.sparseCheckout true
    - echo "demo-front/demo-grid/deployment.yaml" > .git/info/sparse-checkout

    - git fetch origin $MANIFEST_BRANCH_REPO
    - git checkout -b $MANIFEST_BRANCH_REPO origin/$MANIFEST_BRANCH_REPO

    - 'sed -i "s|image: $CI_REGISTRY_IMAGE:.*|image: $CI_REGISTRY_IMAGE:$IMAGE_TAG|" demo-front/demo-grid/deployment.yaml'

    - git add demo-front/demo-grid/deployment.yaml
    - git commit -m "Update image tag to $IMAGE_TAG [ci skip]" || echo "No changes to commit"
    - git pull --rebase origin $MANIFEST_BRANCH_REPO
    - git push origin $MANIFEST_BRANCH_REPO

#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_AUTHOR != "GitLab CI <ci@planet9.uk>"'

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - cd frontend
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_AUTHOR != "GitLab CI <ci@planet9.uk>"'
