stages:
  - setup
  - trigger

generate-child-pipeline:
  stage: setup
  image:
    name: alpine:3.22.1
    pull_policy: if-not-present

  script:
    - export ENV_NAME=$(basename "$CI_COMMIT_REF_NAME")
    - export ENV_PATH=".gitlab-ci/envs/${ENV_NAME}.env"
    - echo "ENV_PATH = $ENV_PATH"
    - echo "ENV_NAME = $ENV_NAME"
    - echo "CI_COMMIT_REF_NAME = $CI_COMMIT_REF_NAME"
    - if [ ! -f "$ENV_PATH" ]; then ENV_PATH=".gitlab-ci/envs/default.env"; fi

    - echo "Generating pipeline config for $ENV_PATH"

    - cp .gitlab-ci/templates/includes.yml child-pipeline.yml
    - echo "variables:" >> child-pipeline.yml
    - sed 's/^/  /' "$ENV_PATH" >> child-pipeline.yml

    - echo "=== child-pipeline.yml content ==="
    - cat child-pipeline.yml

    - echo "CI_PIPELINE_SOURCE = $CI_PIPELINE_SOURCE" >> env_debug.txt

  artifacts:
    paths:
      - child-pipeline.yml
      - env_debug.txt
    expire_in: 1h

trigger-child-pipeline:
  stage: trigger
  trigger:
    include:
      - artifact: child-pipeline.yml
        job: generate-child-pipeline
    strategy: depend
