variables:
  GIT_CLEAN_FLAGS: -ffdx -e frontend/node_modules/
  IMAGE_TAG: $CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
  GITLAB_TOKEN: $GITLAB_TOKEN

#include:
#  - local: "/frontend/.gitlab-ci/snippets/setup.yml"
#  - local: "/frontend/.gitlab-ci/snippets/lint.yml"

before_script:
  - cd frontend

stages:
#  - setup
#  - lint
#  - build
  - deploy

# build:
#   stage: build
#   image: docker:latest
#   services:
#     - docker:dind
#   variables:
#     DOCKER_TLS_CERTDIR: ""

#   before_script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

#   script:
#     - cd frontend
#     - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
#     - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG    
  
#  only:
#    - main

deploy:
  stage: deploy
#  image: alpine/git:v2.47.2

  script:
    - 'git init repo'
    - 'cd repo'
    - 'git remote add origin https://oauth2:$GITLAB_TOKEN@gitlab.planet9.uk/i88/i88-frontend.git'
    - git config core.sparseCheckout true
    - echo "k8s/deployment.yaml" > .git/info/sparse-checkout
    - git pull origin main
    - 'sed -i "s|image: $CI_REGISTRY_IMAGE:.*|image: $CI_REGISTRY_IMAGE:$IMAGE_TAG|" k8s/deployment.yaml'
    - git config user.email "ci@planet9.uk"
    - git config user.name "GitLab CI"
    - git add k8s/deployment.yaml
    - git commit -m "Update image tag to $IMAGE_TAG" || echo "No changes to commit"
    - git push origin main
    
  # only:
  #   - main