const a = [
	{
		'key': 'symbol',
		'label': 'Symbol',
		'shortLabel': 'Sym',
		'position': 0,
		'sortable': true,
		'draggable': false,
		'visible': true,
		'type': 'image-string',
		'group': {
			'name': 'Symbol',
			'displayName': 'Symbol',
		},
	},
	{
		'key': 'priceCurrent',
		'label': 'Current Price',
		'shortLabel': 'Curr',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'number',
		'group': {
			'name': 'Price',
			'displayName': 'Price',
		},
	},
	{
		'key': 'changePrice24hPercent',
		'label': '24h Price Change (%)',
		'shortLabel': 'Δ24h%',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'percent',
		'group': {
			'name': 'Price change',
			'displayName': 'Price change',
		},
	},
	{
		'key': 'volume24h',
		'label': '24h Volume',
		'shortLabel': 'Vol24h',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'number',
		'group': {
			'name': 'Volume',
			'displayName': 'Volume',
		},
	},
	{
		'key': 'priceAvg50d',
		'label': '50d Avg Price',
		'shortLabel': '50d Avg',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'number',
		'group': {
			'name': 'Other',
			'displayName': 'Other',
		},
	},
	{
		'key': 'price1yRange',
		'label': '1y Price Range',
		'shortLabel': '1y Range',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'date',
		'group': {
			'name': 'Other',
			'displayName': 'Other',
		},
	},
	{
		'key': 'marketCap24h',
		'label': '24h Market Cap',
		'shortLabel': 'MCap24h',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'number',
		'group': {
			'name': 'Market cap',
			'displayName': 'Market cap',
		},
	},
	{
		'key': 'beta5y',
		'label': '5y Beta',
		'shortLabel': 'Beta5y',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'number',
		'group': {
			'name': 'Beta',
			'displayName': 'Beta',
		},
	},
	{
		'key': 'lastDividend',
		'label': 'Last Dividend',
		'shortLabel': 'Div',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'number',
		'group': {
			'name': 'Last dividend',
			'displayName': 'Last dividend',
		},
	},
	{
		'key': 'changePrice24h',
		'label': '24h Price Change',
		'shortLabel': 'Δ24h',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'number',
		'group': {
			'name': 'Price change',
			'displayName': 'Price change',
		},
	},
	{
		'key': 'volumeAvg10d',
		'label': '10d Avg Volume',
		'shortLabel': 'Avg10d',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'number',
		'group': {
			'name': 'Volume',
			'displayName': 'Volume',
		},
	},
	{
		'key': 'employees',
		'label': 'Employees',
		'shortLabel': 'Emp',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'number',
		'group': {
			'name': 'Company',
			'displayName': 'Company',
		},
	},
	{
		'key': 'ipoDate',
		'label': 'IPO Date',
		'shortLabel': 'IPO',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'date',
		'group': {
			'name': 'Company',
			'displayName': 'Company',
		},
	},
	{
		'key': 'sector',
		'label': 'Sector',
		'shortLabel': 'Sec',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'date',
		'group': {
			'name': 'Company',
			'displayName': 'Company',
		},
	},
	{
		'key': 'industry',
		'label': 'Industry',
		'shortLabel': 'Ind',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'date',
		'group': {
			'name': 'Company',
			'displayName': 'Company',
		},
	},
	{
		'key': 'source',
		'label': 'Source',
		'shortLabel': 'Src',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'date',
		'group': {
			'name': 'Source',
			'displayName': 'Source',
		},
	},
	{
		'key': 'price24hChart',
		'label': '24h Price Chart',
		'shortLabel': '24h Chart',
		'position': 0,
		'sortable': true,
		'draggable': true,
		'visible': true,
		'type': 'date',
		'group': {
			'name': 'Price chart',
			'displayName': 'Price chart',
		},
	},
];

const b = [
	{
		'id': 'BTC',
		'data': {
			'symbol': {
				'symbolType': 'Crypto',
				'srcImg': '1',
				'ticker': 'ADA',
				'blockchain': 'Example Blockchain',
			},
			'priceCurrent': {
				'value': '137.4',
				'currencySymbol': '$',
				'magnitude': 'B',
			},
			'priceAvg50d': {
				'value': '37.43',
				'currencySymbol': '$',
				'magnitude': 'B',
			},
			'price24hChart': {
				'value': '-',
			},
			'changePrice24h': {
				'value': '72.45',
				'currencySymbol': '$',
				'magnitude': 'B',
			},
			'changePrice24hPercent': {
				'value': '0',
			},
			'volume24h': {
				'value': '11.43',
				'currencySymbol': '$',
				'magnitude': 'B',
			},
			'volumeAvg10d': {
				'value': '23',
				'currencySymbol': '$',
				'magnitude': 'B',
			},
			'marketCap24h': {
				'value': '72.45',
				'currencySymbol': '$',
				'magnitude': 'B',
			},
			'beta5y': {
				'value': '37.45',
				'currencySymbol': '$',
				'magnitude': 'B',
			},
			'lastDividend': {
				'value': '72.45',
				'currencySymbol': '$',
				'magnitude': 'B',
			},
			'employees': {
				'value': '2',
			},
			'ipoDate': {
				'value': '27.09.2002',
			},
			'sector': {
				'value': 'Some sector',
			},
			'industry': {
				'value': 'Some industry',
			},
			'source': {
				'value': 'Some source',
			},
		},
	},
];
