
syntax = "proto3";

package proto;

option go_package = "gitlab.dev-api.tech/api_gateway/pkg/proto/gRPC_auto_generate";

service DataFetchingService {
    rpc GetInstrumentsInfo(stream InstrumentsInfoRequest) returns (stream InstrumentInfoResponse);
}

message InstrumentsInfoRequest {
    Event event=1;
    repeated string instruments=2;
}

enum Event {
    Subscribe=0;
    Unsubscribe=1;
}

message InstrumentInfoResponse {
    string ticker=1;
    string name=2;
    double last=3;
    double change=4;
    double changesPercentage=5;
    double volume=6;
    double relVolume=7;
    double marketCap=8;
    string sector=9;
}