.lint_configuration:
  stage: lint
  image:
    name: node:24.4.1-alpine
    pull_policy: if-not-present

  dependencies:
    - install_dependencies

lint_uscode:
  extends: .lint_configuration
  script:
    - npm run lint

  rules:
    - if: $DISABLE_LINT == "true" || $SKIP_ALL_JOBS == "true"
      when: never
    - when: on_success
