install_dependencies:
  stage: setup
  image:
    name: node:25.2.1-alpine
    pull_policy: if-not-present

  script:
    - npm ci

  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull-push

  # artifacts:
  #   paths:
  #     - node_modules/
  #   expire_in: 1h

  rules:
    - if: $SKIP_ALL_JOBS == "true"
      when: never
    - when: on_success
