/* eslint-disable @stylistic/max-len */
import { WidgetType } from '../widget';
import type { PresetLayout } from './types';

export const MAIN_DASHBOARD_PRESET: PresetLayout = {
	2: [
		{ id: 'price-main', defaultStateType: 'crypto', type: WidgetType.Price, position: { x: 0, y: 0, size: { w: 2, h: 3 } } },
		{ id: 'fear-greed-main', type: WidgetType.FearGreed, position: { x: 0, y: 3, size: { w: 2, h: 4 } } },
		{ id: 'market-cap-main', type: WidgetType.MarketCap, position: { x: 0, y: 7, size: { w: 2, h: 6 } } },
		{ id: 'watchlist-main', type: WidgetType.Watchlist, position: { x: 0, y: 13, size: { w: 2, h: 7 } } },
		{ id: 'bitcoin-dominance-main', type: WidgetType.BitcoinDominance, position: { x: 0, y: 20, size: { w: 2, h: 7 } } },
		{ id: 'altcoin-season-main', type: WidgetType.AltcoinSeason, position: { x: 0, y: 27, size: { w: 2, h: 3 } } },
		{ id: 'news-main', type: WidgetType.News, position: { x: 0, y: 30, size: { w: 2, h: 4 } } },
		{ id: 'market-main', type: WidgetType.Market, position: { x: 0, y: 34, size: { w: 2, h: 8 } } },
	],
	4: [
		{ id: 'price-main', defaultStateType: 'crypto', type: WidgetType.Price, position: { x: 0, y: 0, size: { w: 1, h: 3 } } },
		{ id: 'price-secondary', defaultStateType: 'forex', type: WidgetType.Price, position: { x: 1, y: 0, size: { w: 1, h: 3 } } },
		{ id: 'price-tertiary', defaultStateType: 'stock', type: WidgetType.Price, position: { x: 2, y: 0, size: { w: 1, h: 3 } } },
		{ id: 'fear-greed-main', type: WidgetType.FearGreed, position: { x: 3, y: 0, size: { w: 1, h: 3 } } },
		{ id: 'market-cap-main', type: WidgetType.MarketCap, position: { x: 0, y: 3, size: { w: 2, h: 6 } } },
		{ id: 'altcoin-season-main', type: WidgetType.AltcoinSeason, position: { x: 2, y: 3, size: { w: 2, h: 3 } } },
		{ id: 'market-main', type: WidgetType.Market, position: { x: 0, y: 9, size: { w: 2, h: 8 } } },
		{ id: 'bitcoin-dominance-main', type: WidgetType.BitcoinDominance, position: { x: 2, y: 6, size: { w: 2, h: 7 } } },
		{ id: 'news-main', type: WidgetType.News, position: { x: 2, y: 13, size: { w: 2, h: 4 } } },
		{ id: 'watchlist-main', type: WidgetType.Watchlist, position: { x: 0, y: 17, size: { w: 4, h: 7 } } },
	],
	6: [
		{ id: 'price-main', defaultStateType: 'crypto', type: WidgetType.Price, position: { x: 0, y: 0, size: { w: 1, h: 3 } } },
		{ id: 'price-secondary', defaultStateType: 'forex', type: WidgetType.Price, position: { x: 1, y: 0, size: { w: 1, h: 3 } } },
		{ id: 'price-tertiary', defaultStateType: 'stock', type: WidgetType.Price, position: { x: 2, y: 0, size: { w: 2, h: 3 } } },
		{ id: 'fear-greed-main', type: WidgetType.FearGreed, position: { x: 4, y: 0, size: { w: 2, h: 3 } } },
		{ id: 'market-cap-main', type: WidgetType.MarketCap, position: { x: 0, y: 3, size: { w: 2, h: 6 } } },
		{ id: 'altcoin-season-main', type: WidgetType.AltcoinSeason, position: { x: 2, y: 3, size: { w: 2, h: 7 } } },
		{ id: 'market-main', type: WidgetType.Market, position: { x: 0, y: 9, size: { w: 2, h: 8 } } },
		{ id: 'bitcoin-dominance-main', type: WidgetType.BitcoinDominance, position: { x: 2, y: 10, size: { w: 2, h: 7 } } },
		{ id: 'news-main', type: WidgetType.News, position: { x: 4, y: 3, size: { w: 2, h: 7 } } },
		{ id: 'watchlist-main', type: WidgetType.Watchlist, position: { x: 4, y: 10, size: { w: 2, h: 7 } } },
	],
	8: [
		{ id: 'price-main', defaultStateType: 'crypto', type: WidgetType.Price, position: { x: 0, y: 0, size: { w: 1, h: 4 } } },
		{ id: 'price-secondary', defaultStateType: 'forex', type: WidgetType.Price, position: { x: 1, y: 0, size: { w: 1, h: 4 } } },
		{ id: 'price-tertiary', defaultStateType: 'stock', type: WidgetType.Price, position: { x: 2, y: 0, size: { w: 3, h: 4 } } },
		{ id: 'fear-greed-main', type: WidgetType.FearGreed, position: { x: 5, y: 0, size: { w: 1, h: 4 } } },
		{ id: 'market-cap-main', type: WidgetType.MarketCap, position: { x: 0, y: 4, size: { w: 3, h: 6 } } },
		{ id: 'altcoin-season-main', type: WidgetType.AltcoinSeason, position: { x: 3, y: 4, size: { w: 3, h: 17 } } },
		{ id: 'market-main', type: WidgetType.Market, position: { x: 0, y: 10, size: { w: 3, h: 11 } } },
		{ id: 'bitcoin-dominance-main', type: WidgetType.BitcoinDominance, position: { x: 6, y: 0, size: { w: 2, h: 7 } } },
		{ id: 'news-main', type: WidgetType.News, position: { x: 6, y: 7, size: { w: 2, h: 6 } } },
		{ id: 'watchlist-main', type: WidgetType.Watchlist, position: { x: 6, y: 13, size: { w: 2, h: 8 } } },
	],
	10: [
		{ id: 'price-main', defaultStateType: 'crypto', type: WidgetType.Price, position: { x: 0, y: 0, size: { w: 1, h: 4 } } },
		{ id: 'price-secondary', defaultStateType: 'forex', type: WidgetType.Price, position: { x: 1, y: 0, size: { w: 2, h: 4 } } },
		{ id: 'price-tertiary', defaultStateType: 'stock', type: WidgetType.Price, position: { x: 3, y: 0, size: { w: 3, h: 4 } } },
		{ id: 'fear-greed-main', type: WidgetType.FearGreed, position: { x: 6, y: 0, size: { w: 1, h: 4 } } },
		{ id: 'market-cap-main', type: WidgetType.MarketCap, position: { x: 0, y: 4, size: { w: 4, h: 6 } } },
		{ id: 'altcoin-season-main', type: WidgetType.AltcoinSeason, position: { x: 4, y: 4, size: { w: 3, h: 17 } } },
		{ id: 'market-main', type: WidgetType.Market, position: { x: 0, y: 10, size: { w: 4, h: 11 } } },
		{ id: 'bitcoin-dominance-main', type: WidgetType.BitcoinDominance, position: { x: 7, y: 0, size: { w: 3, h: 7 } } },
		{ id: 'news-main', type: WidgetType.News, position: { x: 7, y: 7, size: { w: 3, h: 6 } } },
		{ id: 'watchlist-main', type: WidgetType.Watchlist, position: { x: 7, y: 13, size: { w: 3, h: 8 } } },
	],
	12: [
		{ id: 'price-main', defaultStateType: 'crypto', type: WidgetType.Price, position: { x: 0, y: 0, size: { w: 1, h: 4 } } },
		{ id: 'price-secondary', defaultStateType: 'forex', type: WidgetType.Price, position: { x: 1, y: 0, size: { w: 2, h: 4 } } },
		{ id: 'price-tertiary', defaultStateType: 'stock', type: WidgetType.Price, position: { x: 3, y: 0, size: { w: 5, h: 4 } } },
		{ id: 'fear-greed-main', type: WidgetType.FearGreed, position: { x: 8, y: 0, size: { w: 1, h: 4 } } },
		{ id: 'market-cap-main', type: WidgetType.MarketCap, position: { x: 0, y: 4, size: { w: 5, h: 6 } } },
		{ id: 'altcoin-season-main', type: WidgetType.AltcoinSeason, position: { x: 5, y: 4, size: { w: 4, h: 17 } } },
		{ id: 'market-main', type: WidgetType.Market, position: { x: 0, y: 10, size: { w: 5, h: 11 } } },
		{ id: 'bitcoin-dominance-main', type: WidgetType.BitcoinDominance, position: { x: 9, y: 0, size: { w: 3, h: 8 } } },
		{ id: 'news-main', type: WidgetType.News, position: { x: 9, y: 8, size: { w: 3, h: 6 } } },
		{ id: 'watchlist-main', type: WidgetType.Watchlist, position: { x: 9, y: 14, size: { w: 3, h: 7 } } },
	],
	14: [
		{ id: 'fear-greed-main', type: WidgetType.FearGreed, position: { x: 9, y: 0, size: { w: 1, h: 3 } } },
		{ id: 'price-main', defaultStateType: 'crypto', type: WidgetType.Price, position: { x: 0, y: 0, size: { w: 2, h: 3 } } },
		{ id: 'price-secondary', defaultStateType: 'forex', type: WidgetType.Price, position: { x: 2, y: 0, size: { w: 2, h: 3 } } },
		{ id: 'price-tertiary', defaultStateType: 'stock', type: WidgetType.Price, position: { x: 4, y: 0, size: { w: 3, h: 3 } } },
		{ id: 'altcoin-season-main', type: WidgetType.AltcoinSeason, position: { x: 6, y: 3, size: { w: 4, h: 21 } } },
		{ id: 'altcoin-season-secondary', type: WidgetType.AltcoinSeason, position: { x: 7, y: 0, size: { w: 2, h: 3 } } },
		{ id: 'news-main', type: WidgetType.News, position: { x: 10, y: 9, size: { w: 4, h: 8 } } },
		{ id: 'bitcoin-dominance-main', type: WidgetType.BitcoinDominance, position: { x: 10, y: 0, size: { w: 4, h: 9 } } },
		{ id: 'market-cap-main', type: WidgetType.MarketCap, position: { x: 0, y: 3, size: { w: 6, h: 9 } } },
		{ id: 'market-main', type: WidgetType.Market, position: { x: 0, y: 12, size: { w: 6, h: 12 } } },
		{ id: 'watchlist-main', type: WidgetType.Watchlist, position: { x: 10, y: 17, size: { w: 4, h: 7 } } },
	],
	16: [
		{ id: 'fear-greed-main', type: WidgetType.FearGreed, position: { x: 11, y: 0, size: { w: 2, h: 4 } } },
		{ id: 'price-main', defaultStateType: 'crypto', type: WidgetType.Price, position: { x: 0, y: 0, size: { w: 2, h: 4 } } },
		{ id: 'price-secondary', defaultStateType: 'forex', type: WidgetType.Price, position: { x: 2, y: 0, size: { w: 2, h: 4 } } },
		{ id: 'price-tertiary', defaultStateType: 'stock', type: WidgetType.Price, position: { x: 4, y: 0, size: { w: 5, h: 4 } } },
		{ id: 'altcoin-season-main', type: WidgetType.AltcoinSeason, position: { x: 7, y: 4, size: { w: 6, h: 21 } } },
		{ id: 'altcoin-season-secondary', type: WidgetType.AltcoinSeason, position: { x: 9, y: 0, size: { w: 2, h: 4 } } },
		{ id: 'news-main', type: WidgetType.News, position: { x: 13, y: 9, size: { w: 3, h: 8 } } },
		{ id: 'bitcoin-dominance-main', type: WidgetType.BitcoinDominance, position: { x: 13, y: 0, size: { w: 3, h: 9 } } },
		{ id: 'market-cap-main', type: WidgetType.MarketCap, position: { x: 0, y: 4, size: { w: 7, h: 9 } } },
		{ id: 'market-main', type: WidgetType.Market, position: { x: 0, y: 13, size: { w: 7, h: 12 } } },
		{ id: 'watchlist-main', type: WidgetType.Watchlist, position: { x: 13, y: 17, size: { w: 3, h: 8 } } },
	],
	20: [
		{ id: 'fear-greed-main', type: WidgetType.FearGreed, position: { x: 13, y: 0, size: { w: 2, h: 6 } } },
		{ id: 'price-main', defaultStateType: 'crypto', type: WidgetType.Price, position: { x: 0, y: 0, size: { w: 2, h: 6 } } },
		{ id: 'price-secondary', defaultStateType: 'forex', type: WidgetType.Price, position: { x: 2, y: 0, size: { w: 2, h: 6 } } },
		{ id: 'price-tertiary', defaultStateType: 'stock', type: WidgetType.Price, position: { x: 4, y: 0, size: { w: 6, h: 6 } } },
		{ id: 'altcoin-season-main', type: WidgetType.AltcoinSeason, position: { x: 10, y: 6, size: { w: 5, h: 27 } } },
		{ id: 'altcoin-season-secondary', type: WidgetType.AltcoinSeason, position: { x: 10, y: 0, size: { w: 3, h: 6 } } },
		{ id: 'news-main', type: WidgetType.News, position: { x: 15, y: 11, size: { w: 5, h: 11 } } },
		{ id: 'bitcoin-dominance-main', type: WidgetType.BitcoinDominance, position: { x: 15, y: 0, size: { w: 5, h: 11 } } },
		{ id: 'market-cap-main', type: WidgetType.MarketCap, position: { x: 0, y: 6, size: { w: 10, h: 10 } } },
		{ id: 'market-main', type: WidgetType.Market, position: { x: 0, y: 16, size: { w: 10, h: 17 } } },
		{ id: 'watchlist-main', type: WidgetType.Watchlist, position: { x: 15, y: 22, size: { w: 5, h: 11 } } },
	],
};
