.lint_configuration:
  stage: lint
  image: node:22.13.0-alpine

  dependencies:
    - install_dependencies

lint_uscode:
  extends: .lint_configuration
  script:
    - npm run lint
    
  rules:
    - if: '$CI_COMMIT_REF_NAME != "main"'
      when: always