apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-front
  namespace: demo-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-front
  template:
    metadata:
      labels:
        app: demo-front
    spec:
      containers:
        - name: demo-front
          image: gitlab.planet9.uk:5050/i88/i88-frontend:main-05e4463d
          ports:
            - containerPort: 8082
      imagePullSecrets:
        - name: gitlab-registry