export enum IconIds {
	Logo = 'logo',
	FearGreedHalfCircle = 'fear-greed-half-circle',
	ControlMore = 'control-more',
	ControlShare = 'control-share',
	Home = 'home',
	Chart = 'chart',
	Calendar = 'calendar',
	ControlRightMenu = 'control-right-menu',
	AddWidget = 'add-widget',
	Plus = 'plus',
	Search = 'search',
	Loosers = 'loosers',
	Gainers = 'gainers',
	Drag = 'drag',
	Retry = 'retry',
}
