import { TimeZoneUTC } from './timezone';

export const timeZoneToDisplay: Record<TimeZoneUTC, string> = {
	[TimeZoneUTC.UTCm12]: 'UTC-12',
	[TimeZoneUTC.UTCm11]: 'UTC-11',
	[TimeZoneUTC.UTCm10]: 'UTC-10',
	[TimeZoneUTC.UTCm930]: 'UTC-9:30',
	[TimeZoneUTC.UTCm9]: 'UTC-9',
	[TimeZoneUTC.UTCm8]: 'UTC-8',
	[TimeZoneUTC.UTCm7]: 'UTC-7',
	[TimeZoneUTC.UTCm6]: 'UTC-6',
	[TimeZoneUTC.UTCm5]: 'UTC-5',
	[TimeZoneUTC.UTCm4]: 'UTC-4',
	[TimeZoneUTC.UTCm330]: 'UTC-3:30',
	[TimeZoneUTC.UTCm3]: 'UTC-3',
	[TimeZoneUTC.UTCm2]: 'UTC-2',
	[TimeZoneUTC.UTCm1]: 'UTC-1',
	[TimeZoneUTC.UTC0]: 'UTC+0',
	[TimeZoneUTC.UTCp1]: 'UTC+1',
	[TimeZoneUTC.UTCp2]: 'UTC+2',
	[TimeZoneUTC.UTCp3]: 'UTC+3',
	[TimeZoneUTC.UTCp330]: 'UTC+3:30',
	[TimeZoneUTC.UTCp4]: 'UTC+4',
	[TimeZoneUTC.UTCp430]: 'UTC+4:30',
	[TimeZoneUTC.UTCp5]: 'UTC+5',
	[TimeZoneUTC.UTCp530]: 'UTC+5:30',
	[TimeZoneUTC.UTCp545]: 'UTC+5:45',
	[TimeZoneUTC.UTCp6]: 'UTC+6',
	[TimeZoneUTC.UTCp630]: 'UTC+6:30',
	[TimeZoneUTC.UTCp7]: 'UTC+7',
	[TimeZoneUTC.UTCp8]: 'UTC+8',
	[TimeZoneUTC.UTCp845]: 'UTC+8:45',
	[TimeZoneUTC.UTCp9]: 'UTC+9',
	[TimeZoneUTC.UTCp930]: 'UTC+9:30',
	[TimeZoneUTC.UTCp10]: 'UTC+10',
	[TimeZoneUTC.UTCp1030]: 'UTC+10:30',
	[TimeZoneUTC.UTCp11]: 'UTC+11',
	[TimeZoneUTC.UTCp12]: 'UTC+12',
	[TimeZoneUTC.UTCp1245]: 'UTC+12:45',
	[TimeZoneUTC.UTCp13]: 'UTC+13',
	[TimeZoneUTC.UTCp14]: 'UTC+14',
};

export const timeZoneFilters = Object.entries(timeZoneToDisplay).map(([key, value]) => ({
	value: key as TimeZoneUTC,
	label: value,
}));
