certificate: |
  -----BEGIN CERTIFICATE-----
  MIIE3zCCAsegAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCkxEDAOBgNVBAoMB2k4
  OF9kZXYxFTATBgNVBAMMDGNmZF9wbGF0Zm9ybTAeFw0yNTAyMDUxMTI1MzBaFw00
  NTAyMDUxMTI1MzBaMCkxEDAOBgNVBAoMB2k4OF9kZXYxFTATBgNVBAMMDGNmZF9w
  bGF0Zm9ybTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALsu7IgI+I5q
  DzlI2ks7DqSuig9wgXzd/xpxD9MaYNmOx6kLkMFO4oJEZJbYmoSjJpUfOklVDtUl
  ZfP0hk0vLi/jks9Tq/annIrGICGEdvJ145BZ4owzfxTdlLGWJOJxHIcSX5MVvivd
  G+7xbfejl7GofvlIs2cMcubEDEMdugcoR/lnfou6Qi0ehLqkN2+J6I2pbz4Sso9a
  +GanpVpNvb5KxQy6UGL+thEYKiuXAyx+UCrlq7PJ+9h13PIQosKepIumcThXt8oG
  nku+/JsFgPIJ65Wu1vUtFdcyb9zuRFeLqjXwxoHp4RS5VcXUSibpVrVbtIVo69fT
  AIT+Lq76Zhb3Nkf8iWKHSCyjxvEYjwTIlhjrrv1Zy/UVLQNePoCdvw5WFOZwYpcJ
  ujIUAgUkrd9QHAOpzo/IbVzB8ylLle8vyPpshIJOZqMGhpkfOxTkhwKFv1fKc/jx
  eEc6sM/7kynJPqtA2u8ULbO2Vs07rOrfRz9SoTiiF31mCYAUBGnWSrrYNtP/C+GH
  lqIRS81yELJiN3ULtuP24oQwkVPLJcMiabdgo4ZPzikN/T6yN8CZRfDm65PqHQYS
  ewEZCAd3xsci+2M1FDqsnwF9ysHExJCyGDfmLKlVdiUTlUY9ATGgjQYMsbD3/hkG
  oSGx7XmdDQ07Wl4698X6Bl+PrmAn1kMpAgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAw
  DQYJKoZIhvcNAQELBQADggIBAH8QZZDfWhmEYB80D4TJmfNByHsWDI8cCrPYth+P
  qGT+XJ8zRVdiFJB/+GKBqonIrTN2TzCnWKS+KHLz5fZ2MEUziwcvJyckieU/f6A5
  RMpkk9FGFF65YrBv91LqjQ8jig1XxjeLS6kNFl/4uuige0JbgpByJnXQZ3gh6by2
  ODWwA47H5bZDe68Y9Kmq1kX7+Tf/ATMIDEqK7WuUVu8d3M4ntF7N32BV7KhKK2NW
  lSASBxMl2l8gaQGk6riuwu5N4Njs/Badwm0AP/gVrOIhAa1mknxiuGiuUmppbKwU
  tyXdbZ6hSIIT4kDU9Ob8qRUCuoMm9Q6c5IBWcgTrZOfoLWhN0anPX6so7gEOQBGK
  DbmPpRTgFK80WZ/fMnga4GoQkPTO1xkgduKpzymJixj0LIVBtAbRmX1/ZdyAY6MA
  Ur5ITdzR7J5ItkESuo3AdKr2WpylIQBJztmcVfOSVtYy0RTh+Vox1XxCiFfXupf6
  CxNMuzO/iSmcYhpuvuA5+6DGR3P8zYoX1+8zJbTeLkvkHMkuqeV8mC5bAMs2N9LW
  9QTGEtFGbO1QBsLLcXByVD4p8y5gmW9nMzdQk/X7OHso2UBb/OAUUBFoo9kgv4B2
  +78zsbb2zYzjUJBWeFnh1EFPKvHFtwyO5FBa1w+yfkUvXcmOd8bI8g8XYJqPeRYo
  9mfh
  -----END CERTIFICATE-----
endpoint: "http://localhost:8000"
client_id: "some_client_id"
client_secret: "some_client_secret"
organization: "i88_dev"
application: "cfd_platform"
