stages:
  - setup
  - lint
  - app_build
  - build_and_deploy
  - deploy
  - dummy

include:
  - local: .gitlab-ci/snippets/setup.yml
  - local: .gitlab-ci/snippets/lint.yml

app_build:
  stage: app_build
  image: node:25.2.1-alpine
  cache:
    key:
      files:
        - package-lock.json
        - src/
    paths:
      - node_modules/
      - dist/
  dependencies:
    - install_dependencies
  script:
    - VERSION=$(node -p "require('./package.json').version")
    - MAJOR_MINOR=$(echo $VERSION | cut -d. -f1,2)
    - NEW_VERSION="$MAJOR_MINOR.$CI_PIPELINE_IID"
    - npm version $NEW_VERSION --no-git-tag-version
    - |
      if [ "$CI_COMMIT_BRANCH" != "main" ]; then
        cp .gitlab-ci/envs/front_config/.env.dev .env || true
        # DEBUG=vite:* NODE_OPTIONS="--trace-warnings" npm run build
        npm run build
      fi
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        # Сборка для stage
        cp .gitlab-ci/envs/front_config/.env.stage .env || true
        npm run build
        # DEBUG=vite:* NODE_OPTIONS="--trace-warnings" npm run build
        mv dist dist-stage
        cp .gitlab-ci/envs/front_config/.env.prod .env || true
        npm run build
        # DEBUG=vite:* NODE_OPTIONS="--trace-warnings" npm run build
        mv dist dist-prod
      fi
  artifacts:
    paths:
      - dist/
      - dist-stage/
      - dist-prod/
    expire_in: 1h
  rules:
    - if: $DISABLE_DEPLOY == "true" || $SKIP_ALL_JOBS == "true"
      when: never
    - when: on_success

build:
  stage: build_and_deploy
  image:
    name: docker:29.1.3-dind
    pull_policy: if-not-present
  services:
    - name: docker:29.1.3-dind
      pull_policy: if-not-present
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILDKIT: "0"
    IMAGE_TAG: $CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
  dependencies:
    - app_build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - CI_COMMIT_SANITIZED="${CI_COMMIT_REF_NAME//\//-}"
    - export IMAGE_TAG="$CI_COMMIT_SANITIZED-$CI_PIPELINE_IID"
# Сборка для всех веток (кроме main) с .env.dev
    - |
      if [ "$CI_COMMIT_BRANCH" != "main" ]; then
        docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
        docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
      fi
# Дополнительные сборки для main
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
      	rm -rf dist
        mv dist-stage dist
        docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
        docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

        rm -rf dist
        mv dist-prod dist
        docker build -t $CI_REGISTRY_IMAGE:prod-$CI_PIPELINE_IID .
        docker push $CI_REGISTRY_IMAGE:prod-$CI_PIPELINE_IID
      fi
  # artifacts:
  #   paths:
  #     - dist/
  #   expire_in: 1h
  rules:
    - if: $DISABLE_DEPLOY == "true" || $SKIP_ALL_JOBS == "true"
      when: never
    - when: on_success

# тут отход от стандарта
deploy_prod:
  stage: deploy
  image:
    name: alpine:3.22.2
    pull_policy: if-not-present
  dependencies: []
  needs:
    - job: build
      artifacts: false
  variables:
    IMAGE_TAG: prod-$CI_PIPELINE_IID
    DEPLOYMENT_PATH: "prod/frontend/deployment.yaml"
  allow_failure: true
  timeout: 1h
  resource_group: publish-npm-${CI_COMMIT_SHA}
  script:
    - CI_COMMIT_SANITIZED="${CI_COMMIT_REF_NAME//\//-}"
    - apk add --no-cache git
    - git init repo
    - cd repo
    - git config user.email "ci@planet9.uk"
    - git config user.name "GitLab CI"
    - git remote add origin https://oauth2:$GITLAB_TOKEN@gitlab.planet9.uk/devops/k8s-manifests.git
    - git config core.sparseCheckout true
    - echo "$DEPLOYMENT_PATH" > .git/info/sparse-checkout
    - git fetch origin main
    - git checkout -b main origin/main
    - 'echo "Deploy file path: $DEPLOYMENT_PATH"'
    - 'sed -i "s|image: $CI_REGISTRY_IMAGE:.*|image: $CI_REGISTRY_IMAGE:$IMAGE_TAG|" $DEPLOYMENT_PATH'
    - git add "$DEPLOYMENT_PATH"
    - git commit -m "Update image tag to $IMAGE_TAG [ci skip]" || echo "No changes to commit"
    - git push origin main
    - echo "Debug:"
    - echo "DEPLOYMENT_PATH = $DEPLOYMENT_PATH"
    - echo "CI_REGISTRY_IMAGE = $CI_REGISTRY_IMAGE"
    - echo "IMAGE_TAG = $IMAGE_TAG"
    - echo "CI_PIPELINE_SOURCE = $CI_PIPELINE_SOURCE"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && ($DISABLE_DEPLOY != "true" && $SKIP_ALL_JOBS != "true")'
      when: manual
      allow_failure: false
    - when: never

deploy:
  stage: deploy
  image:
    name: alpine:3.22.2
    pull_policy: if-not-present
  dependencies: []
  # needs:
  #   - job: build
  #     artifacts: false
  variables:
    IMAGE_TAG: $CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
  script:
    - CI_COMMIT_SANITIZED="${CI_COMMIT_REF_NAME//\//-}"
    - export IMAGE_TAG="$CI_COMMIT_SANITIZED-$CI_PIPELINE_IID"
    - apk add --no-cache git
    - git init repo
    - cd repo
    - git config user.email "ci@planet9.uk"
    - git config user.name "GitLab CI"
    - git remote add origin https://oauth2:$GITLAB_TOKEN@gitlab.planet9.uk/devops/k8s-manifests.git
    - git config core.sparseCheckout true
    - echo "$DEPLOYMENT_PATH" > .git/info/sparse-checkout
    - git fetch origin main
    - git checkout -b main origin/main
    - 'sed -i "s|image: $CI_REGISTRY_IMAGE:.*|image: $CI_REGISTRY_IMAGE:$IMAGE_TAG|" "$DEPLOYMENT_PATH"'
    - git add "$DEPLOYMENT_PATH"
    - git commit -m "Update image tag to $IMAGE_TAG [ci skip]" || echo "No changes to commit"
    - git push origin main
    - echo "Debug:"
    - echo "DEPLOYMENT_PATH = $DEPLOYMENT_PATH"
    - echo "CI_REGISTRY_IMAGE = $CI_REGISTRY_IMAGE"
    - echo "IMAGE_TAG = $IMAGE_TAG"
    - echo "CI_PIPELINE_SOURCE = $CI_PIPELINE_SOURCE"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && ($DISABLE_DEPLOY != "true" && $SKIP_ALL_JOBS != "true")'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "dev" && ($DISABLE_DEPLOY != "true" && $SKIP_ALL_JOBS != "true")'
    - if: '$CI_COMMIT_BRANCH =~ /^sandbox\/.+$/ && ($DISABLE_DEPLOY != "true" && $SKIP_ALL_JOBS != "true")'
      when: on_success
    - when: never

dummy:
  stage: dummy
  script: echo "Nothing to do, skipping..."
  rules:
    - if: '$SKIP_ALL_JOBS == "true"'
      when: on_success
