stages:
  - setup
  - lint
  - build_and_deploy
  - dummy

include:
  - local: .gitlab-ci/snippets/setup.yml
  - local: .gitlab-ci/snippets/lint.yml

variables:
  DEPLOYMENT_PATH_PROD: "prod/frontend/deployment.yaml"

build_prod:
  stage: build_and_deploy
  image:
    name: docker:28.3.2-dind
    pull_policy: if-not-present
  services:
    - name: docker:28.3.2-dind
      pull_policy: if-not-present
  variables:
    DOCKER_TLS_CERTDIR: ""
    IMAGE_TAG: prod-$CI_PIPELINE_IID
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
#    - CI_COMMIT_SANITIZED="${CI_COMMIT_REF_NAME//\//-}"
#    - export IMAGE_TAG="$CI_COMMIT_SANITIZED-$CI_PIPELINE_IID"
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && ($DISABLE_BUILD != "true" && $SKIP_ALL_JOBS != "true")'
      when: on_success
    - when: never

build_stage:
  stage: build_and_deploy
  image:
    name: docker:28.3.2-dind
    pull_policy: if-not-present
  services:
    - name: docker:28.3.2-dind
      pull_policy: if-not-present
  variables:
    DOCKER_TLS_CERTDIR: ""
    IMAGE_TAG: $CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - CI_COMMIT_SANITIZED="${CI_COMMIT_REF_NAME//\//-}"
    - export IMAGE_TAG="$CI_COMMIT_SANITIZED-$CI_PIPELINE_IID"
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  rules:
    - if: $DISABLE_BUILD == "true" || $SKIP_ALL_JOBS == "true"
      when: never
    - when: on_success

# тут отход от стандарта
deploy_prod:
  stage: build_and_deploy
  image:
    name: alpine:3.22.1
    pull_policy: if-not-present
  dependencies: []
  needs:
    - job: build_prod
      artifacts: false
  variables:
    IMAGE_TAG: prod-$CI_PIPELINE_IID
  script:
    - CI_COMMIT_SANITIZED="${CI_COMMIT_REF_NAME//\//-}"
#    - export IMAGE_TAG="$CI_PIPELINE_IID"
    - apk add --no-cache git
    - git init repo
    - cd repo
    - git config user.email "ci@planet9.uk"
    - git config user.name "GitLab CI"
    - git remote add origin https://oauth2:$GITLAB_TOKEN@gitlab.planet9.uk/devops/k8s-manifests.git
    - git config core.sparseCheckout true
    - echo "$DEPLOYMENT_PATH_PROD" > .git/info/sparse-checkout
    - git fetch origin main
    - git checkout -b main origin/main
    - 'sed -i "" "s|image: $CI_REGISTRY_IMAGE:.*|image: $CI_REGISTRY_IMAGE:$IMAGE_TAG|" $DEPLOYMENT_PATH'
    - git add "$DEPLOYMENT_PATH_PROD"
    - git commit -m "Update image tag to $IMAGE_TAG [ci skip]" || echo "No changes to commit"
    - git push origin main
    - echo "Debug:"
    - echo "DEPLOYMENT_PATH = $DEPLOYMENT_PATH_PROD"
    - echo "CI_REGISTRY_IMAGE = $CI_REGISTRY_IMAGE"
    - echo "IMAGE_TAG = $IMAGE_TAG"
    - echo "CI_PIPELINE_SOURCE = $CI_PIPELINE_SOURCE"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && ($DISABLE_DEPLOY != "true" && $SKIP_ALL_JOBS != "true")'
      when: on_success
    - when: never

deploy_stage:
  stage: build_and_deploy
  image:
    name: alpine:3.22.1
    pull_policy: if-not-present
  dependencies: []
  needs:
    - job: build_stage
      artifacts: false
  variables:
    IMAGE_TAG: $CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
  script:
    - CI_COMMIT_SANITIZED="${CI_COMMIT_REF_NAME//\//-}"
    - export IMAGE_TAG="$CI_COMMIT_SANITIZED-$CI_PIPELINE_IID"
    - apk add --no-cache git
    - git init repo
    - cd repo
    - git config user.email "ci@planet9.uk"
    - git config user.name "GitLab CI"
    - git remote add origin https://oauth2:$GITLAB_TOKEN@gitlab.planet9.uk/devops/k8s-manifests.git
    - git config core.sparseCheckout true
    - echo "$DEPLOYMENT_PATH" > .git/info/sparse-checkout
    - git fetch origin main
    - git checkout -b main origin/main
    - echo "DEPLOYMENT_PATH = $DEPLOYMENT_PATH"
    - ls -laR
    - ls -l "$DEPLOYMENT_PATH"
    - cat $DEPLOYMENT_PATH
    - 'echo "image: $CI_REGISTRY_IMAGE:.*|image: $CI_REGISTRY_IMAGE:$IMAGE_TAG| $DEPLOYMENT_PATH"'
    - sed -i "" "s|image: $(echo $CI_REGISTRY_IMAGE | sed 's/:/\\:/g'):.*|image: $CI_REGISTRY_IMAGE:$IMAGE_TAG|" "$DEPLOYMENT_PATH" || (echo "sed failed" && exit 1)
#    - 'sed -i "" "s|image: $CI_REGISTRY_IMAGE:.*|image: $CI_REGISTRY_IMAGE:$IMAGE_TAG|" "$DEPLOYMENT_PATH"'
    - git add "$DEPLOYMENT_PATH"
    - git commit -m "Update image tag to $IMAGE_TAG [ci skip]" || echo "No changes to commit"
    - git push origin main
    - echo "Debug:"
    - echo "DEPLOYMENT_PATH = $DEPLOYMENT_PATH"
    - echo "CI_REGISTRY_IMAGE = $CI_REGISTRY_IMAGE"
    - echo "IMAGE_TAG = $IMAGE_TAG"
    - echo "CI_PIPELINE_SOURCE = $CI_PIPELINE_SOURCE"
  rules:
    - if: $DISABLE_DEPLOY == "true" || $SKIP_ALL_JOBS == "true"
      when: never
    - when: on_success



# deploy:
#   stage: deploy
#   image:
#     name: alpine:3.22.1
#     pull_policy: if-not-present

#   dependencies: [] # отключаем скачивание артефактов
#   variables:
#     IMAGE_TAG: $CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
#   script:
#     - CI_COMMIT_SANITIZED="${CI_COMMIT_REF_NAME//\//-}"
#     - export IMAGE_TAG="$CI_COMMIT_SANITIZED-$CI_PIPELINE_IID"
#     - apk add --no-cache git
#     - git init repo
#     - cd repo
#     - git config user.email "ci@planet9.uk"
#     - git config user.name "GitLab CI"
#     - git remote add origin https://oauth2:$GITLAB_TOKEN@gitlab.planet9.uk/devops/k8s-manifests.git
#     - git config core.sparseCheckout true
#     - echo "$DEPLOYMENT_PATH" > .git/info/sparse-checkout
#     - git fetch origin main
#     - git checkout -b main origin/main

#     - 'sed -i "s|image: $CI_REGISTRY_IMAGE:.*|image: $CI_REGISTRY_IMAGE:$IMAGE_TAG|" $DEPLOYMENT_PATH'
#     - git add "$DEPLOYMENT_PATH"
#     - git commit -m "Update image tag to $IMAGE_TAG [ci skip]" || echo "No changes to commit"
#     - git push origin main

#     - echo "Debug:"
#     - echo "DEPLOYMENT_PATH = $DEPLOYMENT_PATH"
#     - echo "CI_REGISTRY_IMAGE = $CI_REGISTRY_IMAGE"
#     - echo "IMAGE_TAG = $IMAGE_TAG"
#     - echo "CI_PIPELINE_SOURCE = $CI_PIPELINE_SOURCE"

#   rules:
#     - if: $DISABLE_DEPLOY == "true" || $SKIP_ALL_JOBS == "true"
#       when: never
#     - when: on_success

# build:
#   stage: build
#   image:
#     name: docker:28.3.2-dind
#     pull_policy: if-not-present
#   services:
#     - name: docker:28.3.2dind
#       pull_policy: if-not-present
#   variables:
#     DOCKER_TLS_CERTDIR: ""
#     IMAGE_TAG: $CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
#   before_script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   script:
#     - CI_COMMIT_SANITIZED="${CI_COMMIT_REF_NAME//\//-}"
#     - export IMAGE_TAG="$CI_COMMIT_SANITIZED-$CI_PIPELINE_IID"
#     - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
#     - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
#   rules:
#     - if: $DISABLE_BUILD == "true" || $SKIP_ALL_JOBS == "true"
#       when: never
#     - when: on_success

dummy:
  stage: dummy
  script: echo "Nothing to do, skipping..."
  rules:
    - if: '$SKIP_ALL_JOBS == "true"'
      when: on_success
