// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api_gateway.proto

package gRPC_auto_generate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataFetchingService_GetInstrumentsInfo_FullMethodName = "/proto.DataFetchingService/GetInstrumentsInfo"
)

// DataFetchingServiceClient is the client API for DataFetchingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataFetchingServiceClient interface {
	GetInstrumentsInfo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InstrumentsInfoRequest, InstrumentInfoResponse], error)
}

type dataFetchingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataFetchingServiceClient(cc grpc.ClientConnInterface) DataFetchingServiceClient {
	return &dataFetchingServiceClient{cc}
}

func (c *dataFetchingServiceClient) GetInstrumentsInfo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InstrumentsInfoRequest, InstrumentInfoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataFetchingService_ServiceDesc.Streams[0], DataFetchingService_GetInstrumentsInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstrumentsInfoRequest, InstrumentInfoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataFetchingService_GetInstrumentsInfoClient = grpc.BidiStreamingClient[InstrumentsInfoRequest, InstrumentInfoResponse]

// DataFetchingServiceServer is the server API for DataFetchingService service.
// All implementations must embed UnimplementedDataFetchingServiceServer
// for forward compatibility.
type DataFetchingServiceServer interface {
	GetInstrumentsInfo(grpc.BidiStreamingServer[InstrumentsInfoRequest, InstrumentInfoResponse]) error
	mustEmbedUnimplementedDataFetchingServiceServer()
}

// UnimplementedDataFetchingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataFetchingServiceServer struct{}

func (UnimplementedDataFetchingServiceServer) GetInstrumentsInfo(grpc.BidiStreamingServer[InstrumentsInfoRequest, InstrumentInfoResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetInstrumentsInfo not implemented")
}
func (UnimplementedDataFetchingServiceServer) mustEmbedUnimplementedDataFetchingServiceServer() {}
func (UnimplementedDataFetchingServiceServer) testEmbeddedByValue()                             {}

// UnsafeDataFetchingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataFetchingServiceServer will
// result in compilation errors.
type UnsafeDataFetchingServiceServer interface {
	mustEmbedUnimplementedDataFetchingServiceServer()
}

func RegisterDataFetchingServiceServer(s grpc.ServiceRegistrar, srv DataFetchingServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataFetchingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataFetchingService_ServiceDesc, srv)
}

func _DataFetchingService_GetInstrumentsInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataFetchingServiceServer).GetInstrumentsInfo(&grpc.GenericServerStream[InstrumentsInfoRequest, InstrumentInfoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataFetchingService_GetInstrumentsInfoServer = grpc.BidiStreamingServer[InstrumentsInfoRequest, InstrumentInfoResponse]

// DataFetchingService_ServiceDesc is the grpc.ServiceDesc for DataFetchingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataFetchingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DataFetchingService",
	HandlerType: (*DataFetchingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetInstrumentsInfo",
			Handler:       _DataFetchingService_GetInstrumentsInfo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api_gateway.proto",
}
